[project]
name = "stasiak-at"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "pelican-sitemap>=1.1.0",
    "pelican>=4.10.0",
    "typogrify>=2.0.7",
    "invoke>=2.2.0",
    "livereload>=2.7.1",
]
